import { icon, iconNames } from './kit/icons.js';
import { initLighthouse, toast, openDialog, closeDialog } from './kit/lighthouse.js';

const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const esc = value => String(value).replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const button = (label, variant='primary', extra='', ico='') => `<button class="lh-button lh-button--${variant}" ${extra}>${ico ? icon(ico) : ''}<span>${label}</span></button>`;
const badge = (label, tone='info', ico='') => `<span class="lh-badge lh-badge--${tone}">${ico ? icon(ico) : ''}${label}</span>`;
const panelHeader = (title, dismiss = false) => `<header class="lh-panel__header"><img class="header-lighthouse" src="assets/lighthouse.png" alt=""><h4 class="lh-panel__title">${title}</h4><button class="lh-panel__close" aria-label="${dismiss ? 'Закрыть окно' : 'Открыть пример окна'}" ${dismiss ? 'data-lh-close-dialog' : 'data-lh-open-dialog="demo-dialog"'}>${icon('close')}</button></header>`;
const sectionHeading = (num, title, code, caption='') => `<div class="section-heading"><div class="section-title"><span class="number">${num}</span><h3>${title}</h3></div><div class="section-actions"><span class="section-caption">${caption}</span><button class="code-trigger" data-code="${code}">${icon('code')}<span>Код</span></button></div></div>`;
const birds = `<svg class="bird" aria-hidden="true" viewBox="0 0 40 20"><path d="M3 9q9-11 17 1Q29-1 37 9" stroke="currentColor" fill="none" stroke-width="5" stroke-linecap="round"/></svg><svg class="bird second" aria-hidden="true" viewBox="0 0 40 20"><path d="M3 9q9-11 17 1Q29-1 37 9" stroke="currentColor" fill="none" stroke-width="5" stroke-linecap="round"/></svg>`;
const nav = [ ['overview','grid','Обзор',''],['buttons','compass','Кнопки','12'],['panels','grid','Панели и окна','5'],['navigation','menu','Навигация',''],['forms','sliders','Поля и управление',''],['progress','rotate','Прогресс и статусы',''],['icons','star','Иконки','42'] ];
const achievements = [ ['wave','Первый свет','Пережить первую волну',true],['moon','Первая ночь','Пережить 5 волн',true],['wind','Держим оборону','Пережить 10 волн',true],['cloud','Любая погода','Пережить 15 волн',true],['owl','Ночная сова','Пережить 50 волн',false],['storm','Непоколебимый','Пережить 75 волн',false] ];
const rewards = [ ['coin','100 монет'],['drop','200 масла'],['gem','300 крист.'],['gem','400 крист.'],['gem','500 крист.'],['lantern','Фонарь'],['lighthouse','Новый маяк'] ];
const initialIconNames = ['lighthouse','wave','moon','wind','cloud','owl','storm','gem','drop','coin','lantern','turret','mine','bolt','bag','shield','target','rotate','flame','burst','gift','check','lock','heart','star','anchor','compass','settings','volume','arrow-right'];
const renderIcon = name => `<button class="icon-tile" data-copy-icon="${name}" aria-label="Скопировать SVG ${name}">${icon(name)}<span>${name}</span></button>`;

$('#app').innerHTML = `
<aside class="sidebar" id="sidebar">
  <a class="brand" href="#overview" aria-label="Lighthouse — обзор">${icon('lighthouse')}<div><strong>Lighthouse</strong><small>GAME UI KIT</small></div></a>
  <div class="nav-label">БИБЛИОТЕКА</div>
  <nav aria-label="Компоненты">${nav.map(([id,ico,label,count],i)=>`<a href="#${id}" class="nav-link${i===0?' active':''}" data-nav="${id}">${icon(ico)}<span>${label}</span>${count?`<span class="nav-count">${count}</span>`:''}</a>`).join('')}</nav>
  <div class="nav-label" style="margin-top:29px">В ИГРУ</div>
  <nav aria-label="Интеграция"><a class="nav-link" href="#playground" data-nav="playground">${icon('expand')}<span>Песочница</span></a><a class="nav-link" href="examples/game.html">${icon('arrow-right')}<span>Пример интеграции</span></a></nav>
  <div class="sidebar-bottom"><div class="sidebar-note">${icon('anchor')}<strong>Готов к отплытию</strong><p>Никаких зависимостей.<br>Только ваши приключения.</p><a href="#integration">Как подключить ${icon('arrow-right')}</a></div><div class="sidebar-version"><span>Версия 1.0.0</span><span>Сделано с заботой</span></div></div>
</aside><button class="mobile-overlay" aria-label="Закрыть навигацию"></button>
<div class="site-shell">
  <header class="topbar"><div class="breadcrumbs"><button class="mobile-menu" aria-label="Открыть навигацию" aria-expanded="false" aria-controls="sidebar">${icon('menu')}</button><span>UI Library</span>${icon('chevron')}<strong id="breadcrumb-current">Обзор компонентов</strong></div><div class="topbar-actions"><span class="local-status">Локальная сборка</span><a class="plain-button" href="lighthouse-uikit.zip" download>${icon('download')}<span>Скачать UIKit</span></a></div></header>
  <main class="main" id="overview">
    <section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><div class="eyebrow"><span></span> A LITTLE OCEAN OF POSSIBILITIES</div><h1 id="hero-title">Маленькие детали.<br>Большие приключения.</h1><p>Живой UI kit с морским характером.<br>Всё, что нужно вашей следующей игре.</p><div class="hero-chips"><span>${icon('check')} Адаптивные компоненты</span><span>${icon('code')} HTML · CSS · JS</span><span>${icon('heart')} Сделано для игр</span></div></div><div class="cloud"></div>${birds}<div class="hero-waterline"></div><img class="hero-art" src="assets/lighthouse.png" alt="Красно-белый маяк на маленьком острове"></section>
    <div class="collection-heading"><div><h2>Коллекция компонентов</h2><p>Один стиль. Любой размер. Ваше приключение.</p></div><span class="small-tag">v1.0</span></div>
    <div class="filterbar" role="group" aria-label="Фильтр компонентов"><button class="filter active" data-filter="all" aria-pressed="true">Все компоненты <b>7</b></button><button class="filter" data-filter="basic" aria-pressed="false">Основные</button><button class="filter" data-filter="game" aria-pressed="false">Игровые</button><button class="filter" data-filter="forms" aria-pressed="false">Формы</button><button class="filter" data-filter="icons" aria-pressed="false">Иконки</button></div>

    <section class="section" id="buttons" data-category="basic">
      ${sectionHeading('01','Кнопки и действия','buttons','Нажмите. Попробуйте. Почувствуйте.')}
      <div class="gallery-grid">
        <article class="demo-surface"><div class="demo-topline"><span>Основные кнопки</span><small>ЦВЕТ И СОСТОЯНИЕ</small></div><div class="demo-content sea"><div class="button-grid"><div class="button-cell"><span class="spec-label">PRIMARY</span>${button('В бой!','primary','data-demo-action="Приключение начинается!"','arrow-right')}</div><div class="button-cell"><span class="spec-label">SUCCESS</span>${button('Сохранить','success','data-demo-action="Изменения сохранены"','check')}</div><div class="button-cell"><span class="spec-label">SECONDARY</span>${button('Снаряжение','secondary','data-jump="panels"','bag')}</div><div class="button-cell"><span class="spec-label">DANGER</span>${button('Покинуть бой','danger','data-lh-open-dialog="demo-dialog"','close')}</div></div><div class="button-states"><div>${button('Обычная','primary','data-demo-action="Обычная кнопка"')}<span class="state-label">Default</span></div><div><button class="lh-button lh-button--primary" aria-pressed="true" data-toggle-demo>Выбрана</button><span class="state-label">Selected</span></div><div>${button('Недоступно','secondary','disabled')}<span class="state-label">Disabled</span></div></div></div></article>
        <article class="demo-surface"><div class="demo-topline"><span>Маленькие, но важные</span><small>ИКОНКИ И РАЗМЕРЫ</small></div><div class="demo-content sand"><span class="spec-label">ICON BUTTONS</span><div class="icon-buttons" style="margin-top:12px">${[['close','danger','Закрыть'],['settings','secondary','Настройки'],['gift','primary','Подарок'],['check','success','Подтвердить'],['volume','secondary','Звук']].map(([ico,tone,label])=>`<button class="lh-button lh-button--${tone} lh-button--icon lh-tooltip" aria-label="${label}" data-tip="${label}" ${ico==='settings'?'data-lh-open-dialog="settings-dialog"':`data-demo-action="${label}"`}>${icon(ico)}</button>`).join('')}</div><div class="demo-divider"></div><span class="spec-label">SIZE VARIANTS</span><div class="size-row"><button class="lh-button lh-button--primary lh-button--sm" data-demo-action="Маленькая кнопка">Маленькая</button><button class="lh-button lh-button--primary" data-demo-action="Средняя кнопка">Средняя</button><button class="lh-button lh-button--primary lh-button--lg" data-demo-action="Большая кнопка">Большая</button></div><div class="hint-line">${icon('expand')} Ширина следует за текстом, высота — за содержимым</div></div></article>
      </div>
    </section>

    <section class="section" id="panels" data-category="game basic">
      ${sectionHeading('02','Панели и игровые окна','panels','Готовые сценарии из ваших референсов')}
      <div class="game-grid">
        <article class="lh-panel game-panel" aria-label="Достижения">${panelHeader('Достижения')}<div class="lh-panel__body"><div class="achievement-list">${achievements.map(([ico,title,desc,done])=>`<div class="achievement"><span class="lh-icon-badge">${icon(ico)}</span><div class="achievement-text"><strong>${title}</strong><small>${desc}</small></div>${badge(done?'Готово':'',''+(done?'success':'muted'),done?'check':'lock')}</div>`).join('')}</div><div class="panel-footnote"><span>Каждая волна — новая история</span><strong>4 / 6</strong></div></div></article>
        <article class="lh-panel game-panel" aria-label="Ежедневные награды">${panelHeader('Новый день — подарок')}<div class="lh-panel__body"><div class="reward-grid">${rewards.map(([ico,label],i)=>`<div class="reward${i===2?' is-today':''}" data-day="${i}"><span class="day">ДЕНЬ ${i+1}</span>${icon(ico)}<strong>${label}</strong><span class="reward-status${i>2?' locked':''}">${icon(i<2?'check':i===2?'gift':'lock')}${i<2?'Получено':i===2?'Сегодня':'Впереди'}</span></div>`).join('')}</div><div class="reward-claim"><p><strong>Серия: 3 дня</strong>Возвращайтесь за новыми подарками</p>${button('Забрать','success','id="claim-reward"','gift')}</div></div></article>
        <article class="lh-panel game-panel equipment-panel">${panelHeader('Маяки и снаряжение')}<div class="lh-panel__body equipment-layout"><div class="equipment-tabs" role="tablist" aria-label="Тип коллекции"><button class="lh-tab" id="collection-lighthouses" role="tab" aria-selected="true" aria-controls="equipment-content" data-collection="lighthouses">${icon('lighthouse')}<span>Маяки</span></button><button class="lh-tab" id="collection-equipment" role="tab" aria-selected="false" aria-controls="equipment-content" tabindex="-1" data-collection="equipment">${icon('bag')}<span>Снаряжение</span></button></div><div class="equipment-cards" id="equipment-content" role="tabpanel" aria-labelledby="collection-lighthouses"></div></div></article>
        <article class="lh-panel game-panel">${panelHeader('Улучшения')}<div class="lh-panel__body"><div class="upgrade-layout"><div class="upgrade-options" role="group" aria-label="Тип улучшения">${[['rotate','Скорость'],['target','Точность'],['flame','Регенерация']].map(([ico,label],i)=>`<button class="upgrade-option${i===0?' active':''}" data-upgrade-type="${i}" aria-pressed="${i===0}">${icon(ico)}<span>${label}</span></button>`).join('')}</div><div class="upgrade-preview"><div class="upgrade-title"><span class="lh-icon-badge" id="upgrade-icon">${icon('rotate')}</span><div><h4 id="upgrade-name">Скорость вращения</h4><div class="lh-level-dots" id="upgrade-dots" aria-label="Уровень 1 из 5">${Array.from({length:5},(_,i)=>`<span class="${i===0?'is-filled':''}"></span>`).join('')}</div></div></div><div class="upgrade-values"><span id="upgrade-current">+2%</span>${icon('arrow-right')}<strong id="upgrade-next">+4%</strong></div></div></div><div class="upgrade-foot">${button('Улучшить · 115','primary','id="upgrade-button"')}<small>Баланс: <span id="balance">1 250</span> ${icon('coin')}<span>·</span><span id="upgrade-level">Уровень 1 / 5</span></small></div></div></article>
        <article class="lh-panel game-panel">${panelHeader('Всё на своих местах')}<div class="lh-panel__body"><div class="loadout-slots" role="group" aria-label="Снаряжение для боя">${[['turret','Турель'],['mine','Мина'],['bolt','Разрядник']].map(([ico,label],i)=>`<button class="loadout-slot${i===0?' selected':''}" data-loadout="${i}" aria-pressed="${i===0}">${icon(ico)}<span>СЛОТ ${i+1}</span></button>`).join('')}</div><div class="loadout-detail"><h4 id="loadout-title">Турель</h4><div class="stats"><span id="loadout-stat1">УРОН 10</span><span id="loadout-stat2">ДАЛЬНОСТЬ 55</span></div><p id="loadout-description">Автоматически атакует ближайшего врага в радиусе действия.</p>${button('Сохранить сборку','success','id="save-build"','check')}</div></div></article>
      </div>
    </section>

    <section class="section" id="navigation" data-category="basic">
      ${sectionHeading('03','Навигация и окна','navigation','Все пути ведут к маяку')}
      <div class="gallery-grid"><article class="demo-surface"><div class="demo-topline"><span>Вкладки</span><small>KEYBOARD FRIENDLY</small></div><div class="demo-content" data-lh-tabs><div class="lh-tabs" role="tablist" aria-label="Раздел игры"><button class="lh-tab" id="nav-port-tab" role="tab" aria-selected="true" aria-controls="nav-port">${icon('anchor')} Порт</button><button class="lh-tab" id="nav-map-tab" role="tab" aria-selected="false" aria-controls="nav-map" tabindex="-1">${icon('compass')} Карта</button><button class="lh-tab" id="nav-shop-tab" role="tab" aria-selected="false" aria-controls="nav-shop" tabindex="-1">${icon('bag')} Лавка</button></div><div class="sample-tab-panel" id="nav-port" role="tabpanel" aria-labelledby="nav-port-tab"><strong>Добро пожаловать домой</strong>Пополните припасы перед следующим путешествием.</div><div class="sample-tab-panel" id="nav-map" role="tabpanel" aria-labelledby="nav-map-tab" hidden><strong>Впереди целый океан</strong>Откройте новые острова и найдите свой маршрут.</div><div class="sample-tab-panel" id="nav-shop" role="tabpanel" aria-labelledby="nav-shop-tab" hidden><strong>Что возьмём с собой?</strong>Улучшения, полезные мелочи и редкие находки.</div></div></article><article class="demo-surface"><div class="demo-topline"><span>Всплывающие окна</span><small>DIALOG & TOOLTIP</small></div><div class="demo-content"><div class="size-row" style="margin-top:0">${button('Открыть окно','secondary','data-lh-open-dialog="demo-dialog"','expand')}${button('Настройки','primary','data-lh-open-dialog="settings-dialog"','settings')}</div><div class="demo-divider"></div><div class="size-row"><span class="lh-tooltip" data-tip="Защищает маяк от первого попадания" tabindex="0">${badge('Щит смотрителя','info','shield')}</span><button class="plain-button" data-demo-action="Ваш прогресс сохранён" data-toast-tone="success">${icon('check')} Показать уведомление</button></div><div class="hint-line">${icon('compass')} Вкладки: ← → · Закрыть окно: Esc</div></div></article></div>
    </section>

    <section class="section" id="forms" data-category="forms">
      ${sectionHeading('04','Поля и управление','forms','Нативные элементы. Знакомое поведение.')}
      <div class="gallery-grid"><article class="demo-surface"><div class="demo-topline"><span>Ваш следующий капитан</span><small>INPUT & SELECT</small></div><form class="demo-content" id="captain-form"><div class="form-grid"><label class="lh-field"><span>Имя капитана</span><input class="lh-input" name="captain" value="Капитан Маяк" required maxlength="60" autocomplete="nickname" placeholder="Как вас зовут?"></label><label class="lh-field"><span>Родной остров</span><select class="lh-select" name="island"><option>Тихая гавань</option><option>Лазурный берег</option><option>Остров ветров</option><option>Туманный мыс</option></select></label><label class="lh-field wide"><span>Девиз команды</span><textarea class="lh-textarea" name="motto" rows="2" placeholder="Светить даже в самый сильный шторм"></textarea></label></div><div class="choices-row"><label class="lh-check"><input type="checkbox" name="tips" checked><span>Советы смотрителя</span></label><label class="lh-check"><input type="checkbox" disabled><span>Скоро в игре</span></label></div><div class="size-row" style="margin-top:19px"><button type="submit" class="lh-button lh-button--secondary lh-button--sm">${icon('check')} Сохранить профиль</button><span id="profile-status" role="status" style="font-size:10px;color:#6597a7"></span></div></form></article><article class="demo-surface"><div class="demo-topline"><span>Настроить под себя</span><small>SWITCH & RANGE</small></div><div class="demo-content"><div class="setting-row"><div><strong>Звуки океана</strong><p>Волны, чайки и тихий ветер</p></div><label class="lh-switch"><input type="checkbox" checked id="ocean-sound" aria-label="Звуки океана"><span></span></label></div><div class="setting-row"><div><strong>Вибрация</strong><p>Чувствуйте каждое попадание</p></div><label class="lh-switch"><input type="checkbox" id="haptics" aria-label="Вибрация"><span></span></label></div><div class="demo-divider"></div><label class="range-label" for="volume-range"><span>Громкость музыки</span><output id="volume-output" for="volume-range">65%</output></label><input type="range" class="lh-range" min="0" max="100" value="65" id="volume-range"><div class="choices-row"><label class="lh-radio"><input type="radio" name="difficulty" value="calm" checked><span>Штиль</span></label><label class="lh-radio"><input type="radio" name="difficulty" value="storm"><span>Шторм</span></label><label class="lh-radio"><input type="radio" name="difficulty" value="hurricane"><span>Ураган</span></label></div></div></article></div>
    </section>

    <section class="section" id="progress" data-category="basic game">
      ${sectionHeading('05','Прогресс и статусы','progress','Каждый маленький шаг имеет значение')}
      <div class="gallery-grid"><article class="demo-surface"><div class="demo-topline"><span>На пути к большему</span><small>PROGRESS & LEVEL</small></div><div class="demo-content"><div class="progress-demo"><div><div class="status-line"><label for="xp-progress">Опыт смотрителя</label><span id="xp-label">650 / 1 000</span></div><progress class="lh-progress" id="xp-progress" value="650" max="1000">65%</progress></div><div><div class="status-line"><label for="health-progress">Прочность маяка</label><span>80 / 100</span></div><progress class="lh-progress lh-progress--success" id="health-progress" value="80" max="100">80%</progress></div><div class="status-line" style="margin:0"><span>Мастерство</span><div class="lh-level-dots" aria-label="Уровень 3 из 5"><span class="is-filled"></span><span class="is-filled"></span><span class="is-filled"></span><span></span><span></span></div></div></div><div class="size-row" style="margin-top:19px">${button('+ 100 опыта','secondary','id="add-xp"','star')}</div></div></article><article class="demo-surface"><div class="demo-topline"><span>Метки и уведомления</span><small>BADGE & TOAST</small></div><div class="demo-content"><div class="pills-row">${badge('Обычный','muted')}${badge('Необычный','success')}${badge('Редкий','info')}${badge('Эпический','epic')}</div><div class="pills-row">${badge('Готово','success','check')}${badge('Закрыто','muted','lock')}${badge('Новинка','warning','star')}</div><div class="toast-example" id="inline-notice">${icon('check')}<div>Прекрасная работа, смотритель!<small>Новый маяк добавлен в вашу коллекцию.</small></div><button data-lh-dismiss aria-label="Скрыть уведомление">${icon('close')}</button></div><div class="hint-line">${icon('heart')} Цвета помогают считывать состояние с первого взгляда</div></div></article></div>
    </section>

    <section class="section" id="icons" data-category="icons">
      ${sectionHeading('06','Маленькие символы большого мира','icons','')}
      <article class="demo-surface"><div class="demo-topline"><span>Предметы, действия и навигация</span><label class="icon-filter">${icon('search')}<input id="icon-search" type="search" placeholder="Найти иконку" aria-label="Поиск иконок"></label></div><div class="demo-content"><div class="icon-grid" id="icon-grid">${initialIconNames.map(renderIcon).join('')}</div><div class="hint-line">${icon('copy')} Нажмите на иконку, чтобы скопировать SVG <button class="code-trigger" id="show-all-icons" style="margin-left:auto">Все ${iconNames.length} ${icon('arrow-right')}</button></div></div></article>
    </section>

    <section class="section" id="playground" data-category="basic forms game">
      ${sectionHeading('07','Место для экспериментов','playground','Потяните за границы привычного')}
      <div class="demo-surface"><div class="demo-content"><div class="playground-bar"><strong>Проверьте гибкость компонентов</strong><div class="playground-controls"><label>Текст<select id="text-mode"><option value="short">Короткий</option><option value="long">Длинный</option><option value="extreme">Без пробелов</option><option value="english">English</option></select></label><label for="width-range">Ширина <input type="range" id="width-range" min="220" max="680" value="380"><output id="width-output">380 px</output></label></div></div><div class="playground-preview"><article class="lh-panel stretch-target" id="stretch-target"><header class="lh-panel__header"><h4 class="lh-panel__title" id="stretch-title">К новым берегам</h4></header><div class="lh-panel__body"><p id="stretch-description">Ваш маяк готов к приключению. Попутного ветра, капитан!</p>${button('Начать путешествие','primary','id="stretch-button" data-demo-action="Попутного ветра, капитан!"','arrow-right')}</div></article></div></div></div>
    </section>

    <section class="section" id="integration">
      ${sectionHeading('08','От первого клика — к вашей игре','integration','')}
      <div class="demo-surface integration-grid"><div class="integration-copy"><h4>Берите. Собирайте. Отплывайте.</h4><p>Подключите стили и добавьте компоненты в интерфейс игры. Обычные HTML-элементы, CSS-переменные и маленький модуль для интерактивности.</p><a class="plain-button" href="examples/game.html">${icon('arrow-right')} Открыть игровой пример</a><a class="plain-button" href="lighthouse-uikit.zip" download>${icon('download')} Скачать библиотеку</a></div><pre class="code-snippet" style="margin:18px">&lt;link rel="stylesheet"
      href="kit/lighthouse.css"&gt;

&lt;button class="lh-button <span class="hl">lh-button--primary</span>"&gt;
  Начать приключение
&lt;/button&gt;</pre></div>
    </section>
    <footer class="footer"><div>${icon('lighthouse')} Lighthouse UI Kit <span>·</span> Маленький мир, большие возможности.</div><span>Создано для ваших игр · v1.0</span></footer>
  </main>
</div>
<dialog class="lh-dialog demo-dialog" id="demo-dialog" aria-labelledby="demo-dialog-title"><div class="lh-panel"><header class="lh-panel__header"><h2 class="lh-panel__title" id="demo-dialog-title">Ненадолго в порт?</h2><button class="lh-panel__close" data-lh-close-dialog aria-label="Закрыть">${icon('close')}</button></header><div class="modal-content"><span class="lh-icon-badge" style="width:64px;height:64px">${icon('anchor')}</span><p>Море подождёт. Сохраним ваше приключение, чтобы вы могли вернуться к нему позже.</p><div class="modal-buttons">${button('Остаться','secondary','data-lh-close-dialog')}${button('Сохранить и выйти','primary','id="confirm-exit"')}</div></div></div></dialog>
<dialog class="lh-dialog demo-dialog" id="settings-dialog" aria-labelledby="settings-dialog-title"><div class="lh-panel"><header class="lh-panel__header"><h2 class="lh-panel__title" id="settings-dialog-title">Настройки</h2><button class="lh-panel__close" data-lh-close-dialog aria-label="Закрыть">${icon('close')}</button></header><div class="modal-content"><div class="setting-row"><strong>Звуки океана</strong><label class="lh-switch"><input type="checkbox" checked id="modal-sound" aria-label="Звуки океана в настройках"><span></span></label></div><label class="lh-field"><span>Качество эффектов</span><select class="lh-select" id="effects-quality"><option>Высокое</option><option>Среднее</option><option>Низкое</option></select></label><div class="modal-buttons">${button('Сохранить','success','id="save-settings"','check')}</div></div></div></dialog>
<dialog class="lh-dialog code-dialog" id="code-dialog" aria-labelledby="code-dialog-title"><div class="lh-panel"><header class="lh-panel__header"><h2 class="lh-panel__title" id="code-dialog-title">Код компонента</h2><button class="lh-panel__close" data-lh-close-dialog aria-label="Закрыть">${icon('close')}</button></header><div class="modal-content"><pre><code id="code-content"></code></pre><div class="modal-buttons"><button class="lh-button lh-button--primary" id="copy-code">${icon('copy')} Скопировать код</button></div></div></div></dialog>
`;

// Snippets use only portable kit classes. None depend on the showcase CSS.
const snippets = {
buttons: `<button class="lh-button lh-button--primary">Начать путешествие</button>\n<button class="lh-button lh-button--success">Сохранить</button>\n<button class="lh-button lh-button--danger">Покинуть бой</button>\n<button class="lh-button lh-button--secondary" disabled>Недоступно</button>\n\n<!-- Sizes: lh-button--sm / lh-button--lg -->\n<!-- Width: auto by default; set width: 100% to fill. -->`,
panels: `<article class="lh-panel">\n  <header class="lh-panel__header">\n    <h2 class="lh-panel__title">Достижения</h2>\n  </header>\n  <div class="lh-panel__body">\n    <div class="lh-row">\n      <div><strong>Первый свет</strong><br>Пережить первую волну</div>\n      <span class="lh-badge lh-badge--success">Готово</span>\n    </div>\n  </div>\n</article>`,
navigation: `<div data-lh-tabs>\n  <div class="lh-tabs" role="tablist" aria-label="Разделы">\n    <button class="lh-tab" id="tab-a" role="tab"\n      aria-selected="true" aria-controls="panel-a">Порт</button>\n    <button class="lh-tab" id="tab-b" role="tab" tabindex="-1"\n      aria-selected="false" aria-controls="panel-b">Карта</button>\n  </div>\n  <div id="panel-a" role="tabpanel" aria-labelledby="tab-a">Ваш порт</div>\n  <div id="panel-b" role="tabpanel" aria-labelledby="tab-b" hidden>Карта</div>\n</div>\n\n<script type="module">\n  import { initLighthouse } from './kit/lighthouse.js';\n  const cleanup = initLighthouse();\n<\/script>`,
forms: `<label class="lh-field">\n  <span>Имя капитана</span>\n  <input class="lh-input" name="captain" placeholder="Как вас зовут?">\n</label>\n\n<label class="lh-switch">\n  <input type="checkbox" aria-label="Звуки океана" checked>\n  <span></span>\n</label>\n\n<label class="lh-check">\n  <input type="checkbox" checked>\n  <span>Советы смотрителя</span>\n</label>`,
progress: `<label for="experience">Опыт смотрителя</label>\n<progress id="experience" class="lh-progress" value="65" max="100">65%</progress>\n\n<span class="lh-badge lh-badge--success">Готово</span>\n\n<script type="module">\n  import { toast } from './kit/lighthouse.js';\n  toast('Новый уровень!', { tone: 'success', duration: 3500 });\n<\/script>`,
icons: `import { icon, iconNames } from './kit/icons.js';\n\n// Decorative SVG, scales with CSS, no image requests.\ndocument.querySelector('#my-button').innerHTML =\n  icon('lighthouse') + '<span>Мой маяк</span>';\n\n// Accessible name goes on the button.\n// iconNames contains all ${iconNames.length} available names.`,
playground: `<!-- No fixed height or image-based cards. -->\n<div style="width: 380px; max-width: 100%">\n  <article class="lh-panel">\n    <header class="lh-panel__header">\n      <h2 class="lh-panel__title">Любая длина заголовка</h2>\n    </header>\n    <div class="lh-panel__body">\n      <p>Текст переносится, панель растёт по содержимому.</p>\n      <button class="lh-button lh-button--primary" style="width:100%">\n        Длинная надпись автоматически займёт несколько строк\n      </button>\n    </div>\n  </article>\n</div>`,
integration: `<link rel="stylesheet" href="kit/lighthouse.css">\n\n<button id="play" class="lh-button lh-button--primary">В бой!</button>\n\n<script type="module">\n  import { initLighthouse, toast } from './kit/lighthouse.js';\n  const cleanup = initLighthouse();\n\n  document.getElementById('play').addEventListener('click', () => {\n    // Connect your game logic here.\n    toast('Попутного ветра!', { tone: 'success' });\n  });\n  // Call cleanup() when removing the UI.\n<\/script>`
};

let collection = 'lighthouses';
let equipped = {lighthouses:0,equipment:0};
const collections = {
  lighthouses: [ ['Гавань','Там, где начинается история','muted','ОБЫЧНЫЙ',''], ['Классика','Надёжный свет в любую погоду','muted','ОБЫЧНЫЙ','blue-lighthouse'], ['Рассвет','Чуть больше солнечного света','success','НЕОБЫЧНЫЙ','gold-lighthouse'] ],
  equipment: [ ['Турель','УРОН 10 · ДАЛЬНОСТЬ 55','muted','ОБЫЧНЫЙ','turret'], ['Мина','УРОН 40 · ОБЛАСТЬ 10','success','НЕОБЫЧНЫЙ','mine'], ['Разрядник','УРОН 25 · ЦЕЛЕЙ 3','info','РЕДКИЙ','bolt'] ]
};
function renderCollection(){
  $('#equipment-content').innerHTML = collections[collection].map(([name,desc,tone,rarity,art],i)=>`<article class="equipment-card${equipped[collection]===i?' equipped':''}"><div class="item-art">${badge(rarity,tone)}${collection==='lighthouses'?`<img src="assets/lighthouse.png" alt="${name}" class="${art}">`:icon(art)}</div><h4>${name}</h4><p>${desc}</p><button class="lh-button lh-button--${equipped[collection]===i?'success':'primary'}" data-equip="${i}" aria-pressed="${equipped[collection]===i}">${equipped[collection]===i?icon('check'):''}<span>${equipped[collection]===i?'Выбрано':'Экипировать'}</span></button></article>`).join('');
}
renderCollection();
initLighthouse();

function setFilter(filter){
  $$('[data-filter]').forEach(el=>{const active=el.dataset.filter===filter;el.classList.toggle('active',active);el.setAttribute('aria-pressed',String(active));});
  $$('[data-category]').forEach(el=>el.hidden=filter!=='all'&&!el.dataset.category.split(' ').includes(filter));
}
function setNav(id){$$('[data-nav]').forEach(el=>el.classList.toggle('active',el.dataset.nav===id));}
function closeMenu(){$('#sidebar').classList.remove('open');$('.mobile-menu').setAttribute('aria-expanded','false');}
function goto(id){setFilter('all');$('#'+id)?.scrollIntoView({behavior:'smooth',block:'start'});setNav(id);closeMenu();}
async function copyText(text){
  try {await navigator.clipboard.writeText(text);toast('Скопировано. Можно переносить в игру.',{tone:'success'});return true;}
  catch {$('#code-content').textContent=text;openDialog($('#code-dialog'));toast('Выделите и скопируйте код из окна.',{tone:'info'});return false;}
}

document.addEventListener('click',event=>{
  const target=event.target.closest('button, a');if(!target)return;
  if(target.matches('[data-demo-action]'))toast(target.dataset.demoAction,{tone:target.dataset.toastTone||'success'});
  if(target.matches('[data-filter]'))setFilter(target.dataset.filter);
  if(target.matches('[data-nav]')){setFilter('all');setNav(target.dataset.nav);closeMenu();}
  if(target.matches('[data-jump]'))goto(target.dataset.jump);
  if(target.matches('[data-code]')){$('#code-content').textContent=snippets[target.dataset.code];openDialog($('#code-dialog'));}
  if(target.matches('[data-copy-icon]'))copyText(icon(target.dataset.copyIcon));
  if(target.matches('[data-toggle-demo]')){const selected=target.getAttribute('aria-pressed')!=='true';target.setAttribute('aria-pressed',String(selected));target.textContent=selected?'Выбрана':'Выбрать';}
  if(target.matches('[data-collection]')){collection=target.dataset.collection;$$('[data-collection]').forEach(el=>{const active=el===target;el.setAttribute('aria-selected',String(active));el.tabIndex=active?0:-1;});$('#equipment-content').setAttribute('aria-labelledby',target.id);renderCollection();}
  if(target.matches('[data-equip]')){equipped[collection]=Number(target.dataset.equip);renderCollection();toast(`${collections[collection][equipped[collection]][0]} — теперь в вашей сборке`,{tone:'success'});document.dispatchEvent(new CustomEvent('lighthouse:equip',{detail:{collection,index:equipped[collection]}}));}
});
$('.equipment-tabs').addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const tabs=$$('[data-collection]');const index=tabs.indexOf(document.activeElement);const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(index+(event.key==='ArrowLeft'?-1:1)+tabs.length)%tabs.length;tabs[next].focus();tabs[next].click();});
$('#copy-code').addEventListener('click',()=>copyText($('#code-content').textContent));
$('.mobile-menu').addEventListener('click',()=>{const open=$('#sidebar').classList.toggle('open');$('.mobile-menu').setAttribute('aria-expanded',String(open));});
$('.mobile-overlay').addEventListener('click',closeMenu);
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu();});
$('#confirm-exit').addEventListener('click',()=>{closeDialog($('#demo-dialog'));toast('Приключение сохранено. До встречи в порту!',{tone:'success'});});
$('#save-settings').addEventListener('click',()=>{$('#ocean-sound').checked=$('#modal-sound').checked;closeDialog($('#settings-dialog'));toast('Настройки сохранены',{tone:'success'});});
$('#ocean-sound').addEventListener('change',event=>$('#modal-sound').checked=event.target.checked);
$('#volume-range').addEventListener('input',event=>$('#volume-output').textContent=`${event.target.value}%`);
$('#captain-form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.target);$('#profile-status').textContent=`${data.get('captain')}, профиль сохранён`;toast('Профиль капитана сохранён',{tone:'success'});});

let claimed=false;
$('#claim-reward').addEventListener('click',()=>{if(claimed)return;claimed=true;const reward=$('[data-day="2"]');reward.classList.remove('is-today');$('.reward-status',reward).innerHTML=icon('check')+'Получено';$('#claim-reward').innerHTML=icon('check')+'<span>Получено</span>';$('#claim-reward').disabled=true;toast('+300 кристаллов! Награда за третий день получена.',{tone:'success'});});
let balance=1250, upgradeType=0;
const upgrades=[{name:'Скорость вращения',icon:'rotate',level:1},{name:'Точность луча',icon:'target',level:1},{name:'Восстановление огня',icon:'flame',level:1}];
function updateUpgrade(){const item=upgrades[upgradeType];const cost=115+(item.level-1)*65;$('#upgrade-icon').innerHTML=icon(item.icon);$('#upgrade-name').textContent=item.name;$('#upgrade-current').textContent=`+${item.level*2}%`;$('#upgrade-next').textContent=item.level===5?'MAX':`+${(item.level+1)*2}%`;$('#upgrade-level').textContent=`Уровень ${item.level} / 5`;$('#balance').textContent=balance.toLocaleString('ru-RU');$('#upgrade-dots').innerHTML=Array.from({length:5},(_,i)=>`<span class="${i<item.level?'is-filled':''}"></span>`).join('');$('#upgrade-dots').setAttribute('aria-label',`Уровень ${item.level} из 5`);$('#upgrade-button').textContent=item.level===5?'Максимальный уровень':`Улучшить · ${cost}`;$('#upgrade-button').disabled=item.level===5||balance<cost;}
$$('[data-upgrade-type]').forEach(el=>el.addEventListener('click',()=>{upgradeType=Number(el.dataset.upgradeType);$$('[data-upgrade-type]').forEach(b=>{b.classList.toggle('active',b===el);b.setAttribute('aria-pressed',String(b===el));});updateUpgrade();}));
$('#upgrade-button').addEventListener('click',()=>{const item=upgrades[upgradeType],cost=115+(item.level-1)*65;if(item.level>=5||balance<cost)return;balance-=cost;item.level++;updateUpgrade();toast(`${item.name}: уровень ${item.level}`,{tone:'success'});});
const loadout=[['Турель','УРОН 10','ДАЛЬНОСТЬ 55','Автоматически атакует ближайшего врага в радиусе действия.'],['Мина','УРОН 40','ОБЛАСТЬ 10','Взрывается, когда враг оказывается рядом. Идеальна для узких проходов.'],['Разрядник','УРОН 25','ЦЕЛЕЙ 3','Электрический разряд перескакивает между тремя ближайшими врагами.']];
let activeLoadout=0;
$$('[data-loadout]').forEach(el=>el.addEventListener('click',()=>{activeLoadout=Number(el.dataset.loadout);$$('[data-loadout]').forEach(b=>{b.classList.toggle('selected',b===el);b.setAttribute('aria-pressed',String(b===el));});['title','stat1','stat2','description'].forEach((key,i)=>$('#loadout-'+key).textContent=loadout[activeLoadout][i]);}));
$('#save-build').addEventListener('click',()=>{toast(`Сборка сохранена: ${loadout[activeLoadout][0]}`,{tone:'success'});document.dispatchEvent(new CustomEvent('lighthouse:build',{detail:{equipment:activeLoadout}}));});
let xp=650;
$('#add-xp').addEventListener('click',()=>{xp+=100;if(xp>=1000){xp-=1000;toast('Новый уровень смотрителя!',{tone:'success'});}$('#xp-progress').value=xp;$('#xp-progress').textContent=`${xp/10}%`;$('#xp-label').textContent=`${xp} / 1 000`;});
$('#icon-search').addEventListener('input',event=>{const query=event.target.value.trim().toLowerCase();const names=iconNames.filter(name=>name.includes(query));$('#icon-grid').innerHTML=names.length?names.map(renderIcon).join(''):'<div class="empty-icons">Иконки не найдены. Попробуйте wave, gift или shield.</div>';});
$('#show-all-icons').addEventListener('click',()=>{$('#icon-grid').innerHTML=iconNames.map(renderIcon).join('');$('#icon-search').value='';$('#show-all-icons').hidden=true;});
const texts={short:['К новым берегам','Ваш маяк готов к приключению. Попутного ветра, капитан!','Начать путешествие'],long:['Настоящее приключение начинается там, где заканчиваются знакомые берега','Море бывает непредсказуемым, поэтому берите с собой команду, хороший запас масла и немного храбрости. Эта панель растёт вместе с текстом, сохраняя рамку и отступы при любой ширине.','Сохранить мою сборку и отправиться навстречу новому большому приключению'],extreme:['Супердлинныйзаголовокбезединогопробеладляпроверкиадаптивности','ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz','Начатьсамоеневероятноеприключениевнашейжизнипрямосейчас'],english:['Set sail for new shores','Your lighthouse is ready for an adventure. Fair winds and following seas, captain!','Start a brand new adventure']};
$('#text-mode').addEventListener('change',event=>{const text=texts[event.target.value];$('#stretch-title').textContent=text[0];$('#stretch-description').textContent=text[1];$('#stretch-button span').textContent=text[2];});
$('#width-range').addEventListener('input',event=>{$('#stretch-target').style.width=`${event.target.value}px`;$('#width-output').textContent=`${event.target.value} px`;});
const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting&&!e.target.hidden);if(visible.length){const id=visible[0].target.id;setNav(id);const item=nav.find(item=>item[0]===id);$('#breadcrumb-current').textContent=item?item[2]:id==='playground'?'Песочница':'Обзор компонентов';}},{rootMargin:'-90px 0px -68% 0px',threshold:0});
$$('#overview, [data-category]').forEach(el=>observer.observe(el));
